export const Auth = {
    USER_LOGIN_INITIATE: 'USER_LOGIN_INITIATE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
    CREATE_CUSTOMER_INITIATE: 'CREATE_CUSTOMER_INITIATE',
    CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_ERROR: 'CREATE_CUSTOMER_ERROR',
    CREATE_ORGANIZATION_INITIATE: 'CREATE_ORGANIZATION_INITIATE',
    CREATE_ORGANIZATION_SUCCESS: 'CREATE_ORGANIZATION_SUCCESS',
    CREATE_ORGANIZATION_ERROR: 'CREATE_ORGANIZATION_ERROR',
    REMOVE_AUTH_TOASTER: "REMOVE_AUTH_TOASTER",
    CLEAR_AUTH_STATE: "CLEAR_AUTH_STATE"
}

export const CustomerActions = {
  organizationsTab: {
    GET_ORGANIZTIONS_INITIATE: "GET_ORGANIZTIONS_INITIATE",
    GET_ORGANIZTIONS_SUCCESS: "GET_ORGANIZTIONS_SUCCESS",
    GET_ORGANIZTIONS_FAILURE: "GET_ORGANIZTIONS_FAILURE",
    SEARCH_ORGANIZTION_INITIATE: "SEARCH_ORGANIZTION_INITIATE",
    SEARCH_ORGANIZTION_SUCCESS: "SEARCH_ORGANIZTION_SUCCESS",
    SEARCH_ORGANIZTION_FAILURE: "SEARCH_ORGANIZTION_FAILURE",
    SEND_UNSEND_REQUEST_INITIATE: "SEND_UNSEND_REQUEST_INITIATE",
    SEND_UNSEND_REQUEST_SUCCESS: "SEND_UNSEND_REQUEST_SUCCESS",
    SEND_UNSEND_REQUEST_FAILURE: "SEND_UNSEND_REQUEST_FAILURE",
    DISCONNECT_FROM_ORG_INITIATE: "DISCONNECT_FROM_ORG_INITIATE",
    DISCONNECT_FROM_ORG_SUCCESS: "DISCONNECT_FROM_ORG_SUCCESS",
    DISCONNECT_FROM_ORG_FAILURE: "DISCONNECT_FROM_ORG_FAILURE",
    REMOVE_CUSTOMER_TAB_TOASTER: "REMOVE_CUSTOMER_TAB_TOASTER"
  },
  menuTab: {
    GET_MENU_INITIATE: "GET_MENU_INITIATE",
    GET_MENU_SUCCESS: "GET_MENU_SUCCESS",
    GET_MENU_FAILURE: "GET_MENU_FAILURE",
    PLACE_ORDER_INITIATE: 'PLACE_ORDER_INITIATE',
    PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
    PLACE_ORDER_FAILURE: 'PLACE_ORDER_FAILURE',
    MENU_TOASTER_REMOVE: "MENU_TOASTER_REMOVE"
  },
  orderstab: {
    GET_ALL_ORDERS_INITIATE: "GET_ALL_ORDERS_INITIATE",
    GET_ALL_ORDERS_SUCCESS: "GET_ALL_ORDERS_SUCCESS",
    GET_ALL_ORDERS_FAILURE: "GET_ALL_ORDERS_FAILURE",
    CANCEL_ORDER_INITIATE: "CANCEL_ORDER_INITIATE",
    CANCEL_ORDER_SUCCESS: "CANCEL_ORDER_SUCCESS",
    CANCEL_ORDER_FAILURE: "CANCEL_ORDER_FAILURE",
    ORDER_TOASTER_REMOVE: "ORDER_TOASTER_REMOVE"
  },
  profileTab: {
    GET_CUSTOMER_PROFILE_INITIATE: "GET_CUSTOMER_PROFILE_INITIATE",
    GET_CUSTOMER_PROFILE_SUCCESS: "GET_CUSTOMER_PROFILE_SUCCESS",
    GET_CUSTOMER_PROFILE_FAILURE: "GET_CUSTOMER_PROFILE_FAILURE",
    UPDATE_CUSTOMER_PROFILE_INITIATE: "UPDATE_CUSTOMER_PROFILE_INITIATE", 
    UPDATE_CUSTOMER_PROFILE_SUCCESS: "UPDATE_CUSTOMER_PROFILE_SUCCESS",
    UPDATE_CUSTOMER_PROFILE_FAILURE: "UPDATE_CUSTOMER_PROFILE_FAILURE",
    UPDATE_CUSTOMER_FAVOURITES_INITIATE: "UPDATE_CUSTOMER_FAVOURITES_INITIATE",
    UPDATE_CUSTOMER_FAVOURITES_SUCCESS: "UPDATE_CUSTOMER_FAVOURITES_SUCCESS",
    UPDATE_CUSTOMER_FAVOURITES_FAILURE: "UPDATE_CUSTOMER_FAVOURITES_FAILURE",
    UPDATE_CUSTOMER_PASSWORD_INITIATE: "UPDATE_CUSTOMER_PASSWORD_INITIATE",
    UPDATE_CUSTOMER_PASSWORD_SUCCESS: "UPDATE_CUSTOMER_PASSWORD_SUCCESS",
    UPDATE_CUSTOMER_PASSWORD_FAILURE: "UPDATE_CUSTOMER_PASSWORD_FAILURE",
  }
}

export const OrganizationActions = {
  customersTab: {
    GET_CUSTOMERS_INITIATE: "GET_CUSTOMERS_INITIATE",
    GET_CUSTOMERS_SUCCESS: "GET_CUSTOMERS_SUCCESS",
    GET_CUSTOMERS_FAILURE: "GET_CUSTOMERS_FAILURE",
    GET_REQUESTS_INITIATE: "GET_REQUESTS_INITIATE",
    GET_REQUESTS_SUCCESS: "GET_REQUESTS_SUCCESS",
    GET_REQUESTS_FAILURE: "GET_REQUESTS_FAILURE",
    REMOVE_CUSTOMER_INITIATE: "REMOVE_CUSTOMER_INITIATE",
    REMOVE_CUSTOMER_SUCCESS: "REMOVE_CUSTOMER_SUCCESS",
    REMOVE_CUSTOMER_FAILURE: "REMOVE_CUSTOMER_FAILURE",
    ACCEPT_REJECT_CUSTOMER_INITIATE: "ACCEPT_REJECT_CUSTOMER_INITIATE",
    ACCEPT_REJECT_CUSTOMER_SUCCESS: "ACCEPT_REJECT_CUSTOMER_SUCCESS",
    ACCEPT_REJECT_CUSTOMER_FAILURE: "ACCEPT_REJECT_CUSTOMER_FAILURE",
    REMOVE_CUSTOMERS_TOAST: "REMOVE_CUSTOMERS_TOAST"
  },
  menuTab: {
    GET_ORG_MENUS_INITIATE: "GET_ORG_MENUS_INITIATE",
    GET_ORG_MENUS_SUCCESS: "GET_ORG_MENUS_SUCCESS",
    GET_ORG_MENUS_FAILURE: "GET_ORG_MENUS_FAILURE",
    CREATE_NEW_MENU_INITIATE: "CREATE_NEW_MENU_INITIATE",
    CREATE_NEW_MENU_SUCCESS: "CREATE_NEW_MENU_SUCCESS",
    CREATE_NEW_MENU_FAILURE: "CREATE_NEW_MENU_FAILURE",
    MENU_ACTION_INITIATE: "MENU_ACTION_INITIATE",
    MENU_ACTION_SUCCESS: "MENU_ACTION_SUCCESS",
    MENU_ACTION_FAILURE: "MENU_ACTION_FAILURE",
    REMOVE_MENU_TOAST: "REMOVE_MENU_TOAST",
  }
}